autotest/urls.py
from django.urls import path
from .views import *


urlpatterns = [

    path('login/', login, name='login'),
    path('home/', home, name='home'),
    path('logout/', logout, name='logout'),
    path('project_manage/', project_manage, name='project_manage'),
    path('module_manage/', module_manage, name='module_manage'),
    path('suite_manage/', suite_manage, name='suite_manage'),
    path('case_manage/', case_manage, name='case_manage'),
    path('casestep_manage/', casestep_manage, name='casestep_manage'),
    path('case_result_level_one/', case_result_level_one, name='case_result_level_one'),
    path('case_result_level_two/', case_result_level_two, name='case_result_level_two'),
    path('case_result_detail/', case_result_detail, name='case_result_detail'),
    path('base/', base, name='base'),
    path('test/', test, name='test'),
    # 目前先不用
    path('autotest_report/', autotest_report, name='autotest_report'),
    path('project_level_report/', project_level_report, name='project_level_report'),
    path('case_level_report/', case_level_report, name='case_level_report'),
    path('casesearch/', caseSearch, name='caseSearch'),
    path('stepsearch/', caseStepSearch, name='caseStepSearch'),

]

gloryroad_autoplatform/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include(('autotest.urls', 'autotest'), namespace='autotest')),
   # 配置媒体文件的路由地址
    re_path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name = 'media')

]

autotest/views.py
#encoding=utf-8

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
import os
import time
from concurrent.futures import ThreadPoolExecutor
from django.contrib import auth
from .models import TestCaseInfo, ProjectInfo, CaseStepInfo, CaseExecuteResult, ExecuteRecord, ModuleInfo, TestSuiteInfo
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from .utils import runTestCase
from .tasks import runTestCase
from .config import projectPath, screenRelativePath

# Create your views here.

# from .tasks import getBaiDu, runTestCase


# 测试全选
def caseList(request):
    case_list = TestCaseInfo.objects.all()

    return render(request, "testCheckAll.html")


# 搜索功能
@login_required
def caseSearch(request):
    username = request.session.get('user', '') # 从session获取用户
    search_caseName = request.GET.get('casename', '')
    case_list = TestCaseInfo.objects.filter(name__icontains=search_caseName)
    return render(request, 'case_manage.html', {'user': username, 'cases': case_list})

# @login_required
# def caseSubmit(request):
#     if request.method == "POST":
#         case_id_list = request.POST.getlist('testcase')
#         if case_id_list:
#             print("case_id_list: ", case_id_list)
#             response = HttpResponseRedirect('caseSubmit/')
#         else:
#             print("no case_id_list")
#             return HttpResponse("fail")


@login_required
def caseStepSearch(request):
    username = request.session.get('user','') # 读取session
    search_caseName = request.GET.get('caseName', '')
    caseStep_list = CaseStepInfo.objects.filter(case__name__contains=search_caseName)
    print("caseStep_list: %s" % caseStep_list)
    return render(request, 'casestep_manage.html', {'user': username, 'casesteps': caseStep_list})

# 用例管理
@login_required
def case_manage(request):
    if request.method == "POST":
        username = request.session.get('user', '')
        print("username: %s" % username)
        case_id_list = request.POST.getlist('testcase')
        if case_id_list:
            print("case_id_list: ", case_id_list)
            # 获取当前时间点时间戳，用于存储各个用例执行记录的执行id（相同）
            execute_id = int(time.time())
            print("execute_id: %s" % execute_id)
            for caseId in case_id_list:
                # 获取测试用例
                runTestCase.delay(execute_id, caseId, username)
                # with ThreadPoolExecutor(3) as executor:
                #     executor.map(runTestCase, case_id_list)
            return HttpResponse("ok")
        else:
            print("no case_id_list")
            return HttpResponse("fail")
    else:
        case_list = TestCaseInfo.objects.all()
        case_account = TestCaseInfo.objects.all().count() # 统计产品数
        username = request.session.get('user', '')
        paginator = Paginator(case_list, 8) # 生成Paginator对象，设置每页显示8条记录
        page = request.GET.get('page', 1) # 获取当前的页码数，默认为第一页
        currentPage = int(page) # 把获取的当前页数转成整数类型
        try:
            case_list = paginator.page(currentPage) # 获取当前页数的记录列表
        except PageNotAnInteger:
            case_list = paginator.page(1) # 如果输入的页数不是整数，则显示第一页内容
        except EmptyPage:
            case_list = paginator.page(paginator.num_pages) # 如果输入的页数不在系统的页数中，则显示最后一页
        return render(request, "case_manage.html", {'user': username, "cases": case_list, "caseaccounts": case_account})


# 用例步骤
@login_required
def casestep_manage(request):
    username = request.session.get('user', '')
    caseid = request.GET.get('webcase.id', None)
    print("caseid: %s" % caseid)
    testcase = TestCaseInfo.objects.get(id=caseid)
    casestep_list = CaseStepInfo.objects.filter(case_id=caseid).order_by('teststep')
    print("casestep_list: ", casestep_list)
    paginator = Paginator(casestep_list, 8) # 生成paginator对象，设置每页显示8条记录
    page = request.GET.get('page', 1) # 获取当前的页码数，默认为第一页
    currentPage = int(page) # 把获取的当前页码数转成整数类型

    try:
        casestep_list = paginator.page(currentPage)  # 获取当前页数的记录列表
    except PageNotAnInteger:
        casestep_list = paginator.page(1)  # 如果输入的页数不是整数，则显示第一页内容
    except EmptyPage:
        casestep_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数中，则显示最后一页

    return render(request, "casestep_manage.html", {"user": username, "testcase": testcase, "casesteps": casestep_list})



# 用例步骤
@login_required
def suite_manage(request):
    if request.method == "POST":
        username = request.session.get('user', '')
        print("username: %s" % username)
        suite_id_list = request.POST.getlist('testsuite')
        if suite_id_list:
            print("case_id_list: ", suite_id_list)
            # 获取当前时间点时间戳，用于存储各个用例执行记录的执行id（相同）
            execute_id = int(time.time())
            print("execute_id: %s" % execute_id)

            suite_id_case_id_dict = {} # {'1': [1,2,3,4], '2': [1,3,4]}
            for suite_id in suite_id_list:
                case_id_list = []
                suiteInfo = TestSuiteInfo.objects.filter(id=suite_id).first()
                # include_cases = suiteInfo.include_cases
                include_cases = suiteInfo.cases.all()
                print("include_cases: %s" % include_cases)
                # include_cases = eval(include_cases)  # [['1', '登录12306邮箱'], ['2', '登录12306邮箱用例1']]
                # print("include_cases: %s" % include_cases)
                # 获取测试用例id列表
                for case in include_cases:
                    case_id_list.append(case.id) # [1, 2]
                print("case_id_list: %s" % case_id_list)
                # 获取suiteid和用例列表的对应字典
                suite_id_case_id_dict[suite_id] = case_id_list #  {'1': [1,2,3,4], '2': [1,3,4]}
            print("suite_id_case_id_dict: %s" % suite_id_case_id_dict)
            for suite_id, case_id_list in suite_id_case_id_dict.items(): # 遍历suiteid和用例列表关联字典，传入用例执行函数，在执行记录表里记录执行记录和suiteid的关系
                print("case_id_list in for statement: %s" % case_id_list)
                # 获取测试用例
                for case_id in case_id_list:
                    runTestCase.delay(execute_id, case_id, username, suite_id)
                # with ThreadPoolExecutor(3) as executor:
                #     executor.map(runTestCase, case_id_list)
            return HttpResponse("ok")
        else:
            print("no case_id_list")
            return HttpResponse("fail")
    elif request.method == 'GET':
        username = request.session.get('user', '')
        testsuite_data = TestSuiteInfo.objects.all()
        suite_list = []
        for suite in testsuite_data:
            suite_dict = {}
            suite_dict['id'] = suite.id
            suite_dict['suite_name'] = suite.suite_name
            suite_dict['belong_project'] = suite.belong_project.project_name
            suite_dict['belong_module'] = suite.belong_module.module_name
            print("suite.cases.all(): %s" % suite.cases.all())
            # include_cases = eval(suite.include_cases) # [['1', '登录12306邮箱'], ['2', '登录12306邮箱用例1']]
            include_cases = suite.cases.all() # [['1', '登录12306邮箱'], ['2', '登录12306邮箱用例1']]
            print("include_cases: %s" % include_cases)
            include_cases_list = []
            for case in include_cases:
                include_cases_dict = {}
                include_cases_dict['case_id'] =  case.id
                include_cases_dict['case_desc'] =  case.name
                include_cases_list.append(include_cases_dict)
            print("include_cases_list: %s" % include_cases_list)

            suite_dict['include_cases'] = len(include_cases_list) # 暂时取列表的长度，include_cases_list保留
            suite_dict['create_time'] = suite.create_time
            suite_dict['update_time'] = suite.update_time
            suite_list.append(suite_dict)
        print("suite_list: %s" % suite_list)

        paginator = Paginator(suite_list, 8) # 生成paginator对象，设置每页显示8条记录
        page = request.GET.get('page', 1) # 获取当前的页码数，默认为第一页
        currentPage = int(page) # 把获取的当前页码数转成整数类型

        try:
            casestep_list = paginator.page(currentPage)  # 获取当前页数的记录列表
        except PageNotAnInteger:
            casestep_list = paginator.page(1)  # 如果输入的页数不是整数，则显示第一页内容
        except EmptyPage:
            casestep_list = paginator.page(paginator.num_pages)  # 如果输入的页数不在系统的页数中，则显示最后一页

        return render(request, "suite_manage.html", {"user": username, "testsuites": suite_list})



def case_result_level_one(request):

    return render(request, "case_result_level1.html")


# 用例结果
@login_required
def case_result_level_two(request):
    username = request.session.get('user', '')
    runStatus = request.GET.get("alreadyrun", '')
    suiteId = request.GET.get("suiteid", '')
    historySuiteId = request.GET.get("historysuiteid", '')
    # runStatus: 0: 待执行，1： 已执行
    if runStatus:
        print("runStatus: %s" % runStatus)
        case_recored_list = ExecuteRecord.objects.filter(status = 1).order_by('-create_time') if (str(runStatus) == '1') else ExecuteRecord.objects.filter(status=0)
        print("case_recored_list: ", case_recored_list)
        case_list = []
        success_num = 0  # 获取成功用例数，用于填充echart图
        fail_num = 0  # 存储失败用例数，用于填充echart图
        for record in case_recored_list:
            case_dict = {}
            case_info = TestCaseInfo.objects.filter(id = record.case_id).first()
            print("case_info: ,", case_info)
            case_dict["case_id"] = record.case_id
            case_dict["execute_record_id"] = record.id
            case_dict["execute_result"] = '' if not record.execute_result else record.execute_result
            case_dict["exception_info"] = '' if  not record.exception_info else record.exception_info
            case_dict["capture_screen"] = '' if not record.capture_screen else record.capture_screen
            case_dict["execute_start_time"] = record.execute_start_time
            case_dict["belong_module"] = case_info.belong_module.module_name

autotest/templates/case_manage.html
<html lang="zh-CN">
 <head>
{% load static %}
 <title>光荣之路自动化测试平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>

<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>



<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">

<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />



<meta name="robots" content="NONE,NOARCHIVE" />

 </head>
 <body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<ul class="nav justify-content-left"> &nbsp;
</ul>
<ul class="nav justify-content-center"> &nbsp;
</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="/home/">Home</a></li>
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>

<!-- 搜索栏-->
<div class="page-header" style="padding-top: 70px;">
<form class="navbar-form" method="get" action="/casesearch/">

{# {% csrf_token %} #}



<!-- 增加web测试用例-->
<div style="float:right;width:70%">

<!--
<select name="Webcase" id="id_Webcase">
<option value="" selected>----web测试用例----</option>
</select>
-->


</form>
</div>


<script type="text/javascript">
//页面加载的时候,所有的复选框都是未选中的状态
function checkOrCancelAll()
{
    var chElt=document.getElementById("chElt");//1.获取checkbo的元素对象    
    var checkedElt = chElt.checked;//2.获取选中状态
    var allCheck = document.getElementsByClassName("file");//3.若checked=true,将所有的复选框选中,checked=false,将所有的复选框取消

    //var allCheck = document.getElementsByName("file");//方法2
    var mySpan=document.getElementById("mySpan");//4.循环遍历取出每一个复选框中的元素
    if(checkedElt)//全选
    {
        
        for(var i=0;i<allCheck.length;i++)
        {
            //设置复选框的选中状态
            allCheck[i].checked=true;
        }
        mySpan.innerHTML="取消全选";
    }
    else//取消全选
    {
        for(var i=0;i<allCheck.length;i++)
        {
            allCheck[i].checked=false;
        }
        mySpan.innerHTML="全选";
    }
}
function ischecked()
{
    var allCheck = document.getElementsByClassName("file");//3.若checked=true,将所有的复选框选中,checked=false,将所有的复选框取消
    for(var i=0;i<allCheck.length;i++)
    {
        if(allCheck[i].checked == true)
        {
            return true
        }
    }
    alert("请选择用例")
    return false
}
</script>

 <!-- web测试用例列表-->
 <div class="row" style="padding-top: 20px;">
 <div class="col-md-12">
 <table class="table table-striped">
 <thead>
 <tr>

<form action="" method="POST" style="position:absolute; top:10px; left:10px"> 

<input type="checkbox" id="chElt" onclick="checkOrCancelAll();"/><span id="mySpan">全选</span> <br />
<input name="submit" type="submit" onclick="return ischecked()" value="运行" style="position:absolute; top:0px; left:100px" />  <br />

<th>选择</th><th>ID</th><th>所属模块</th><th>用例名称</th><th>负责人</th><th>创建时间</th><th>查看</th><th>编辑</th>

 </tr>
 </thead>
 <tbody>
 {% for webcase in cases %}
 <tr>
 <td><input class="file" type="checkbox" name="testcase" value="{{ webcase.id }}"/></td>
 <td>{{ webcase.id }}</td>
 <td>{{ webcase.belong_module.module_name }}</td>
 <td>{{ webcase.name }}</td>
 <td>{{ webcase.author }}</td>
 <td>{{ webcase.create_time }}</td>
<td><a href="{% url "autotest:casestep_manage" %}?webcase.id={{ webcase.id  }} ">步骤信息</a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="../admin/autotest/testcaseinfo/{{ webcase.id  }}/change/?_to_field=id&_popup=1">编辑</a></td>
 </tr>
 {% endfor %}


</form> 

 </tbody>
 </table>
 </div>
 </div>

<!--统计和翻页功能-->
<span style="position:absolute; left:800px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:500px; bottom:25px; width:100px;">
共:{{ caseaccounts }}条记录 {# 前端读取定义的变量#}
</div>
<div class="container">
    <ul class="pagination" id="pager">
          {# 上一页链接开始#}
        {% if cases.has_previous %}
            {#  如果有上一页则正常显示上一页链接#}
            <li class="previous"><a href="/case_manage/?page={{ cases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
        {% endif %}
        {# 上一页链接开始#}

        {% for num in cases.paginator.page_range %}

            {% if num == currentPage %}
                <li class="item active"><a href="/case_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#}
            {% else %}
                <li class="item"><a href="/case_manage/?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {# 下一页链接开始#}
        {% if cases.has_next %} {#  如果有下一页则正常显示下一页链接#}
            <li class="next"><a href="/case_manage/?page={{ cases.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页链接结束#}
    </ul>
</div>

 </body>
 </html>

autotest/templates/case_result_level2.html
<html lang="zh-CN">
 <head>
{% load static %}
 <title>光荣之路自动化测试平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>

<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>



<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">

<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />

<style>


/*背景层*/
	#popLayer {
		display: none;
		background-color: #B3B3B3;
		{#background-color: #1fc223;#}
		position: absolute;
		top: 0;
		right: 0;
		bottom: 0;
		left: 0;
		z-index: 10;
		-moz-opacity: 0.8;
		opacity:.80;
        width: 100%;
        height: 100%;
		filter: alpha(opacity=80);/* 只支持IE6、7、8、9 */
	}

    /*弹出层，在背景层的上面座椅z-index只要比背景层的z-index大即可*/
	#popBox {
		display: none;
		background-color: #FFFFFF;
		z-index: 11;
		width: 800px;
		height: 400px;
		position:fixed;
		top:0;
		right:0;
		left:0;
		bottom:0;
		margin:auto;
	}
    /* 关闭按钮的样式*/

    #popBox .close{
		text-align: right;
		margin-right: 5px;
		background-color: #F8F8F8;
	}

    /*关闭按钮*/
	#popBox .close a {
		text-decoration: none;
		color: #2D2C3B;
	}
</style>

     <script>
         function handleClickException(content){
             var content = content.getAttribute('tagVal')
             document.getElementById('popContent').innerText = content
             document.getElementById('popLayer').style.display = 'block'
             document.getElementById('popBox').style.display = 'block'
         }

         function closeBox() {
            document.getElementById('popBox').style.display = 'none'
            document.getElementById('popLayer').style.display = 'none'
         }
     </script>

<meta name="robots" content="NONE,NOARCHIVE" />

 </head>
 <body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<ul class="nav justify-content-left"> &nbsp;
</ul>
<ul class="nav justify-content-center"> &nbsp;
</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="/home/">Home</a></li>
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>

<!-- 搜索栏-->
<div class="page-header" style="padding-top: 70px;">
<form class="navbar-form" method="get" action="/casesearch/">

{# {% csrf_token %} #}

<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
<div id="main" style="height:250px"></div>
<!-- ECharts单文件引入 -->
<script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
<script type="text/javascript">
    // 路径配置
    require.config({
        paths: {
            echarts: 'http://echarts.baidu.com/build/dist'
        }
    });

    // 使用
    require(
        [
            'echarts',
            'echarts/chart/pie' // pie是饼图，使用柱状图就加载bar模块，按需加载
        ],
        function (ec) {
            // 基于准备好的dom，初始化echarts图表
            var myChart = ec.init(document.getElementById('main'));

            var option = {
                    tooltip : {
                        trigger: 'item',
                        formatter: "{a} <br/>{b} : {c} ({d}%)"
                    },
                    legend: {
                     orient: 'horizontal', // 'vertical'/horizontal
                        x: 'center', // 'center' | 'left' | {number},
                        y: '230', // 'center' | 'bottom' | {number}
                        {#backgroundColor: '#eee',#}
                        {#borderColor: 'rgba(178,34,34,0.8)',#}
                        {#borderWidth: 4,#}
                        padding: 10,    // [5, 10, 15, 20]
                        itemGap: 20,
                        textStyle: {color: 'red'},
                        data: [
                            '成功用例{{ successnumber }}','失败用例{{ failnumber }}'
                        ]
                     },
                    calculable : true,
                    series : [
                        {
                            name:'用例执行结果',
                            type:'pie',
                            center:['50%', '40%'],
                            radius : ['40%', '70%'],
                            {#selectedOffset: 20,#}
                            itemStyle : {
                                normal : {
                                    label : {
                                        show : false
                                    },
                                    labelLine : {
                                        show : false
                                    }
                                },
                                emphasis : {

                                    label : {
                                        show : true,
                                        position : 'center',
                                        textStyle : {
                                            fontSize : '20',
                                            fontWeight : 'bold'
                                        }
                                    }
                                }
                            },
                            data:[
                                {value:{{ successnumber }}, name:'成功用例{{ successnumber }}'},
                                {value:{{ failnumber }}, name:'失败用例{{ failnumber }}'},
                            ]
                        }
                    ],
                    color: ['#1fc223', '#c22d33', '#c23531', '#c23531']
                };


            // 为echarts对象加载数据
            myChart.setOption(option);
        }
    );
</script>




<!-- 增加web测试用例-->
<div style="float:right;width:70%">

<!--
<select name="Webcase" id="id_Webcase">
<option value="" selected>----web测试用例----</option>
</select>
-->


</form>
</div>

 <tr>
<th>用例执行结果</th>
</tr>

 <!-- web测试用例列表-->
 <div class="row" style="padding-top: 20px;">
 <div class="col-md-12">
 <table class="table table-striped">
 <thead>
 <tr>

<th>ID</th><th>所属模块</th><th>用例名称</th><th>负责人</th><th>创建时间</th><th>执行时间</th><th>执行结果</th><th>执行详情</th>
 </tr>
 </thead>
 <tbody>
 {% for webcase in cases %}
 <tr>
 <td>{{ webcase.case_id }}</td>
 <td>{{ webcase.belong_module }}</td>
 <td>{{ webcase.name }}</td>
 <td>{{ webcase.author }}</td>
 <td>{{ webcase.create_time|date:"Y-m-d H:i:s" }}</td>
 <td>{{ webcase.execute_start_time }}</td>
 <td>{{ webcase.execute_result }}</td>
 <td><a style="color: #0000cc;" href="{% url 'autotest:case_result_detail' %}?caseid={{ webcase.case_id }}&execute_record_id={{ webcase.execute_record_id }}" target="_blank">执行详情</a></td>
 </tr>
 {% endfor %}

 </tbody>
 </table>
 </div>
 <div class="col-md-12">
 <table class="table table-striped">
     {% if suiteid %}
        <th><a style="color: #0000cc;" href="{% url 'autotest:case_result_level_two' %}?historysuiteid={{ suiteid }}" target="_blank">历史记录</a></th>
     {% endif %}

 </table>
 </div>
<!--统计和翻页功能-->
<span>   {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:500px; bottom:25px; width:100px;">
共:{{ caseaccounts }}条记录 {# 前端读取定义的变量#}
</div>
<div class="container">
    <ul class="pagination" id="pager">
          {# 上一页链接开始#}
        {% if cases.has_previous %}
            {#  如果有上一页则正常显示上一页链接#}
            <li class="previous"><a href="/case_result_level_two/?page={{ cases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
        {% endif %}
        {# 上一页链接开始#}

        {% for num in cases.paginator.page_range %}

            {% if num == currentPage %}
                <li class="item active"><a href="/case_result_level_two/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#}
            {% else %}
                <li class="item"><a href="/case_result_level_two/?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {# 下一页链接开始#}
        {% if cases.has_next %} {#  如果有下一页则正常显示下一页链接#}
            <li class="next"><a href="/case_manage/?page={{ cases.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页链接结束#}
    </ul>
</div>

 </body>
 </div>


    <!-- 弹出层 --->
    <div id="popLayer"></div>
    <div id="popBox">
        <div class="close">
            <a href="javascript:void(0)" onclick="closeBox()">关闭</a>
        </div>
        <div id="popContent" class="content"></div>
    </div>

 </body>
 </html>